Update Dockerfile

diff --git a/yaml/Dockerfile b/yaml/Dockerfile
--- a/yaml/Dockerfile
+++ b/yaml/Dockerfile
@@ -26,6 +26,17 @@ RUN apk -U upgrade \
     && apk cache clean \
     && rm -rf /var/cache/apk/*
 
+RUN pip3 install --no-cache-dir --upgrade --break-system-packages \
+    json2yaml==1.2.0 \
+    yamllint==1.37.1 \
+    yamlpath==3.8.2 \
+    yq==3.4.3 \
+    && msg="$(pip3 list --outdated | grep -i -e '^json2yaml ' -e '^yamllint ' -e '^yamlpath ' -e '^yq ' || true)" \
+    && if [ -n "${msg}" ]; then \
+       >&2 echo "ERROR: outdated: ${msg}" ; \
+       exit 1 ; \
+    fi
+
 RUN adduser \
   --home "${USER_HOME}" \
   --uid "${USER_ID}" \
@@ -38,14 +49,3 @@ USER "${USER_NAME}"
 ENV HOME="${USER_HOME}"
 
 WORKDIR "${HOME}"
-
-RUN pip3 install --no-cache-dir --upgrade --break-system-packages \
-    json2yaml==1.2.0 \
-    yamllint==1.37.1 \
-    yamlpath==3.8.2 \
-    yq==3.4.3 \
-    && msg="$(pip3 list --outdated | grep -i -e '^json2yaml ' -e '^yamllint ' -e '^yamlpath ' -e '^yq ' || true)" \
-    && if [ -n "${msg}" ]; then \
-       >&2 echo "ERROR: outdated: ${msg}" ; \
-       exit 1 ; \
-    fi
